// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function make() {
  return "";
}

function logStr(str, log) {
  return log + (str + "\n");
}

var print = Pervasives.print_string;

exports.make   = make;
exports.logStr = logStr;
exports.print  = print;
/* No side effect */
