// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var times = Caml_int32.imul;

function square(x) {
  return Caml_int32.imul(x, x);
}

exports.times  = times;
exports.square = square;
/* No side effect */
