// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var $plus = Caml_int32.imul;

var DifferentPlus = /* module */[/* + */$plus];

Pervasives.print_int(18);

exports.DifferentPlus = DifferentPlus;
/*  Not a pure module */
