// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Log$ReasonmlDemoModules = require("./Log.bs.js");

Log$ReasonmlDemoModules.print(Log$ReasonmlDemoModules.logStr("everyone", Log$ReasonmlDemoModules.logStr("Hello", Log$ReasonmlDemoModules.make(/* () */0))));

/*  Not a pure module */
